apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jmeter-cluster
  region: us-west-2

nodeGroups:
  - name: jm-node
    instanceType: t2.small
    desiredCapacity: 5
    privateNetworking: false
    # availabilityZones: ["us-east-1b", "us-east-1c", "us-east-1d", "us-east-1e", "us-east-1f"]
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    tags:
      'environment': 'live'
      'Name': 'live-jmeter-node'
